// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlwdrtybfsqutkwpgcls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sd2RydHliZnNxdXRrd3BnY2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTY1NzQsImV4cCI6MjA3MDA3MjU3NH0.c00xLQR8HwzIvY74BVTs2AzeD0p32Pmjfjkr3zUb8sI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});